[package]
name = "fbx-tree-view"
version = "0.1.0"
authors = ["Takuma YOSHIOKA <tashioka.256@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = "GUI viewer of FBX tree structure"

[dependencies]
fbxcel = "0.0.2"
gdk = "0.9.0"

[dependencies.gtk]
version = "0.5.0"
features = ["v3_16"]
